export const GETPAIRPRICEBYINTERVAL = 'GETPAIRPRICEBYINTERVAL';
export const GETCANDLESBYINTERVAL = 'GETCANDLESBYINTERVAL';
export const CHECKOPENEDSELLTRADES = 'CHECKOPENEDSELLTRADES';
export const BUYERROR = 'BUYERROR';
export const SELLERROR = 'SELLERROR';

