export const GETPAIRPRICEBYINTERVAL = 'GETPAIRPRICEBYINTERVAL';
export const GETCANDLESBYINTERVAL = 'GETCANDLESBYINTERVAL';
export const BUYERROR = 'BUYERROR';
export const GETALLUSERS = 'GETALLUSERS';
