version: '3'
services:
  binance-buy-deep-bot-fe:
    image: binance-buy-deep-bot-fe
    restart: unless-stopped
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - bot_network
  binance-buy-deep-bot:
    image: binance-buy-deep-bot
    restart: unless-stopped
    ports:
      - '5000:5000'
    networks:
      - bot_network

    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - '27017:27017'
    networks:
      - bot_network
    volumes:
      - mongodata:/data/db

networks:
  bot_network:
    driver: bridge

volumes:
  mongodata:
    driver: local
